### ISSUE TITLE
unsolicited: "AT+START=?" doesn't work

### ISSUE THREAD

**Issue by parsley72** [marcinbor85/cAT#21]
I tried the unsolicited demo but when I enter "AT+START=?" I just get "ERROR". The example shows:
```
AT+START=?                                              # TEST command
+START=<MODE:UINT32[WO]>                                # Automatic response
Start scanning after write (0 - wifi, 1 - bluetooth).   # Automatic response
OK                                                      # Automatic acknowledge
```

**Comment by marcinbor85** [comment]
hi. related with buffer size.
this change should help:
![image](https://user-images.githubusercontent.com/6499601/157929840-31c56fa6-2c4a-45f2-aad9-a7a7c8613928.png)

**Comment by LianYangCn** [comment]
> hi. related with buffer size. this change should help: ![image](https://user-images.githubusercontent.com/6499601/157929840-31c56fa6-2c4a-45f2-aad9-a7a7c8613928.png)

not work.

**Comment by LianYangCn** [comment]
> > hi. related with buffer size. this change should help: ![image](https://user-images.githubusercontent.com/6499601/157929840-31c56fa6-2c4a-45f2-aad9-a7a7c8613928.png)
> 
> not work.

Sorry, my fault. 

The CR and LF were eaten before sending to cAT.
It works awesome.
