### ISSUE TITLE
Example of real use case

### ISSUE THREAD

**Issue by MaJerle** [marcinbor85/cAT#34]
Do you have an example how this can be used to communicate with for instance GSM modem?

**Comment by marcinbor85** [comment]
This library is not designed to connect to any host side device. This is for implementing host devices with AT commands. So answering to Your question... there is no such real use case examples with this.

**Comment by marcinbor85** [comment]
No. It's for host side. So for e.g. we can build our own GSM modem or any other device with well defined AT commands protocol.
