### ISSUE TITLE
Endianess handling

### ISSUE THREAD

**Issue by MaJerle** [marcinbor85/cAT#35]
https://github.com/marcinbor85/cAT/blob/2f8929a408717264ad374ec68d41d0805b4a472d/src/cat.c#L1194

How do you handle endianess for non-1-byte-width arrays?

**Comment by marcinbor85** [comment]
There is no need to support such kind of arrays. This bar type is used for decoding hexascii arrays byte streams. What will happen with these bytes later depends on app layer logic.
