### ISSUE TITLE
Support of URC events

### ISSUE THREAD

**Issue by MasoudHD** [marcinbor85/cAT#45]
Hi @marcinbor85,
Thanks for your very useful repository. I was digging into your library to find out if it can support URC events that are not AT-based commands (such as RING in GSM modems). As far as I understood it just can interpret unsolicited AT commands. Is that true? and which parts should I change to add support for these events (if it is possible at all)?
Thank you

**Comment by marcinbor85** [comment]
Hi. Yes there is a possibility to SEND unsolicited events, not interpret
them Keep it mind that this lib is for Host side which serves AT compatible
interface, not Client side.
MB

śr., 9 sie 2023, 13:27 użytkownik Masoud ***@***.***> napisał:
