### ISSUE TITLE
How to model ATE?

### ISSUE THREAD

**Issue by lrds** [marcinbor85/cAT#7]
I am having trouble modeling the ATE command.

Do I have to register **ATE**, **ATE0** and **ATE1** as seperate commands
or is it possible to register ATE\<boolean selector char here\>
and have the parser do a **run** if it sees ATE and a **write** if it sees ATE0 or ATE1?

I see how it'd be possible to do ATE=\<value\>, but it looks a bit non-Hayes to me.

**Comment by marcinbor85** [comment]
Hi.
Unfortunetely, its not possibile. You have to register separated commands
to do that. Everything before = and ? chars is processed as part of command
name. It may be little confusing if this type of command with boolean
selector will be implemented togerher with separated command with same
name. But it could be solved by introduce some limitation im commands name.
If You want I'm open for a pull request with that functionality.
Regards
MB

pt., 22 maj 2020, 08:01 użytkownik Lars Randers <notifications@github.com>
napisał:

**Comment by lrds** [comment]
I played around with it some more and then it struck me.

Although you need to register every variation of the command, like:
```c
struct cat_command cmds[] = {
    {
        .name = "E",
        .run = echo_run
    },
    {
        .name = "E0",
        .run = echo_run
    },
    {
        .name = "E1",
        .run = echo_run
    },
```

you *can* actually register the same run handler and use something along the lines of
```c
static cat_return_state echo_run(const struct cat_command *cmd)
{
    echo_flag = (cmd->name[strlen(cmd->name)-1] == '1') ? 1 : 0;
    return CAT_RETURN_STATE_OK;
}
```
and just look at the value of the last byte of **cmd**->**name**.
That way you save yourself from repeating a lot of handlers with almost the same content. Sweet!

One thing I noted was that the shortest command **has** to be listed first,
otherwise it will not be found by the internal search and the parser will return ERROR.

I hope this helps someone who wanders in here and asks the same question ..:slightly_smiling_face:..

**Comment by marcinbor85** [comment]
Great.
It is the proper solution.

Order of commands should not matter.
I think there can be a bug. I will check that.
But Your solution is good workaround at this moment.

Thanks for a update.


pon., 25 maj 2020, 22:56 użytkownik Lars Randers <notifications@github.com>
napisał:
